#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_TRAY                                102
#define IDM_MAIN                                104
#define IDM_PROCESS                             106
#define IDB_SIDEBAR                             108
#define IDB_ABOUT_SIDEBAR                       110
#define IDB_PAGEUP_DK                           112
#define IDB_PAGEUP_LT                           114
#define IDB_PAGEDN_DK                           116
#define IDB_PAGEDN_LT                           118
#define IDB_START                               120
#define IDB_START_HOVER                         122
#define IDB_STOP                                124
#define IDB_STOP_HOVER                          126
#define CUR_VSPLIT                              128
#define IDS_SIDEBAR                             1001
#define IDE_THIRD_PARTY                         1002
#define IDB_PAGEUP                              1003
#define IDB_PAGEDOWN                            1004
#define IDL_PROCESS                             1005
#define IDL_STATUS                              1006
#define IDT_VIEW                                1007
#define IDB_GOTO                                1008
#define ICO_MAIN                                4096
#define IDM_FILE_CAPTURE                        40000
#define IDM_FILE_STOP                           40001
#define IDM_FILE_EXIT                           40002
#define IDM_VIEW_REALTIME                       40003
#define IDM_VIEW_MONTH                          40004
#define IDM_VIEW_STATISTICS                     40005
#define IDM_VIEW_DETAIL                         40006
#define IDM_VIEW_SHOW_HIDDEN                    40007
#define IDM_OPTIONS_PREFERENCES                 40008
#define IDM_HELP_TOPIC                          40009
#define IDM_HELP_HOMEPAGE                       40010
#define IDM_HELP_ABOUT                          40011
#define IDM_TRAY_SHOW_WINDOW                    40012
#define IDM_TRAY_ABOUT                          40013
#define IDM_TRAY_EXIT                           40014
#define IDM_PROCESS_SHOW                        40015
#define IDM_PROCESS_HIDE                        40016
#define IDB_CLOSE                               40030
#define IDE_GOTO                                40040
#define IDL_DETAIL                              40041
#define IDM_VIEW_ADAPTER_FIRST                  50000
#define IDM_OPTIONS_LANGUAGE_FIRST              51000
#define IDL_PREF_DEFAULT_ADAPTER                51004
#define IDC_PREF_DEFAULT_ADAPTER                51005
#define IDC_PREF_AUTO_START                     51006
#define IDC_PREF_AUTO_CAPTURE                   51007
#define IDG_PREF_DETAIL_VIEW                    51009
#define IDC_PREF_ENABLE                         51010
#define IDC_PREF_MAX_DTVIEW                     51011
#define IDE_PREF_MAX_DTVIEW                     51012
#define IDB_PREF_DELETE_ALL                     51013
#define IDB_PREF_OK                             51014
#define IDB_PREF_CANCEL                         51015
